package constants

// SKUID ENVIRONMENT VARIABLE NAMES
const (
	ENV_SKUID_HOST          = "SKUID_HOST"
	ENV_SKUID_PASSWORD      = "SKUID_PW"
	ENV_SKUID_USERNAME      = "SKUID_UN"
	ENV_SKUID_CLIENT_ID     = "SKUID_CLIENT_ID"
	ENV_SKUID_CLIENT_SECRET = "SKUID_CLIENT_SECRET"
)

// pliny
const (
	ENV_PLINY_HOST = "PLINY_HOST"
)

// SERVICE PROXY ENVIRONMENT VARIABLE NAMES
const (
	ENV_METADATA_SERVICE_PROXY = "METADATA_SERVICE_PROXY"
	ENV_DATA_SERVICE_PROXY     = "DATA_SERVICE_PROXY"
)

// logging and tracing
const (
	ENV_VERBOSE                = "SKUID_VERBOSE"
	ENV_TRACE                  = "SKUID_TRACE"
	ENV_TIDES_LOG              = "SKUID_LOG"
	ENV_TIDES_DEFAULT_FOLDER   = "SKUID_DEFAULT_FOLDER"
	ENV_TIDES_LOGGING_LOCATION = "SKUID_LOGGING_DIRECTORY"
	ENV_TIDES_FILE_LOGGING     = "SKUID_FILE_LOGGING"
	ENV_TIDES_FIELD_LOGGING    = "SKUID_FIELD_LOGGING"
)

const (
	ENV_MARINA_HOST = "MARINA_HOST"
)

const (
	TEST_ENVIRONMENT_FILE = ".testenv"
	ENVIRONMENT_FILE      = ".env"
)

const (
	TIDES_DEFAULT_LOGGING_LOCATION = ".logs"
)
