// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: deployment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarinaClient is the client API for Marina service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarinaClient interface {
	Deployment(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (Marina_DeploymentClient, error)
}

type marinaClient struct {
	cc grpc.ClientConnInterface
}

func NewMarinaClient(cc grpc.ClientConnInterface) MarinaClient {
	return &marinaClient{cc}
}

func (c *marinaClient) Deployment(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (Marina_DeploymentClient, error) {
	stream, err := c.cc.NewStream(ctx, &Marina_ServiceDesc.Streams[0], "/protobuf.Marina/Deployment", opts...)
	if err != nil {
		return nil, err
	}
	x := &marinaDeploymentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Marina_DeploymentClient interface {
	Recv() (*DeploymentResponse, error)
	grpc.ClientStream
}

type marinaDeploymentClient struct {
	grpc.ClientStream
}

func (x *marinaDeploymentClient) Recv() (*DeploymentResponse, error) {
	m := new(DeploymentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarinaServer is the server API for Marina service.
// All implementations must embed UnimplementedMarinaServer
// for forward compatibility
type MarinaServer interface {
	Deployment(*DeploymentRequest, Marina_DeploymentServer) error
	mustEmbedUnimplementedMarinaServer()
}

// UnimplementedMarinaServer must be embedded to have forward compatible implementations.
type UnimplementedMarinaServer struct {
}

func (UnimplementedMarinaServer) Deployment(*DeploymentRequest, Marina_DeploymentServer) error {
	return status.Errorf(codes.Unimplemented, "method Deployment not implemented")
}
func (UnimplementedMarinaServer) mustEmbedUnimplementedMarinaServer() {}

// UnsafeMarinaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarinaServer will
// result in compilation errors.
type UnsafeMarinaServer interface {
	mustEmbedUnimplementedMarinaServer()
}

func RegisterMarinaServer(s grpc.ServiceRegistrar, srv MarinaServer) {
	s.RegisterService(&Marina_ServiceDesc, srv)
}

func _Marina_Deployment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeploymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarinaServer).Deployment(m, &marinaDeploymentServer{stream})
}

type Marina_DeploymentServer interface {
	Send(*DeploymentResponse) error
	grpc.ServerStream
}

type marinaDeploymentServer struct {
	grpc.ServerStream
}

func (x *marinaDeploymentServer) Send(m *DeploymentResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Marina_ServiceDesc is the grpc.ServiceDesc for Marina service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marina_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Marina",
	HandlerType: (*MarinaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deployment",
			Handler:       _Marina_Deployment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployment.proto",
}
