// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the result of getting the plan from the pliny
// deployment retrieval plan endpoint
// type NlxPlanPayload struct {
// 	// Cloud Data Service is WARDEN
// 	CloudDataService NlxPlan `json:"skuidCloudDataService"`
// 	// Metadata Service is PLINY
// 	MetadataService NlxPlan `json:"skuidMetadataService"`
// }
type RetrievalPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudDataService *Plan `protobuf:"bytes,1,opt,name=CloudDataService,proto3" json:"skuidCloudDataService"` // @gotags: json:"skuidCloudDataService"
	MetadataService  *Plan `protobuf:"bytes,2,opt,name=MetadataService,proto3" json:"skuidMetadataService"`   // @gotags: json:"skuidMetadataService"
}

func (x *RetrievalPlan) Reset() {
	*x = RetrievalPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrievalPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalPlan) ProtoMessage() {}

func (x *RetrievalPlan) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalPlan.ProtoReflect.Descriptor instead.
func (*RetrievalPlan) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *RetrievalPlan) GetCloudDataService() *Plan {
	if x != nil {
		return x.CloudDataService
	}
	return nil
}

func (x *RetrievalPlan) GetMetadataService() *Plan {
	if x != nil {
		return x.MetadataService
	}
	return nil
}

// type NlxPlan struct {
// 	Host     string      `json:"host"`
// 	Port     string      `json:"port"`
// 	Endpoint string      `json:"url"`
// 	Type     string      `json:"type"`
// 	Metadata NlxMetadata `json:"metadata"`
// 	Warnings []string    `json:"warnings"`
// }
type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string    `protobuf:"bytes,1,opt,name=Host,proto3" json:"host"`               // @gotags: json:"host"
	Port        string    `protobuf:"bytes,2,opt,name=Port,proto3" json:"port"`               // @gotags: json:"port"
	Endpoint    string    `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"url"`       // @gotags: json:"url"
	Type        string    `protobuf:"bytes,4,opt,name=Type,proto3" json:"type"`               // @gotags: json:"type"
	NlxMetadata *Metadata `protobuf:"bytes,5,opt,name=NlxMetadata,proto3" json:"metadata"` // @gotags: json:"metadata"
	Warnings    []string  `protobuf:"bytes,6,rep,name=Warnings,proto3" json:"warnings"`       // @gotags: json:"warnings"
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Plan) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Plan) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Plan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Plan) GetNlxMetadata() *Metadata {
	if x != nil {
		return x.NlxMetadata
	}
	return nil
}

func (x *Plan) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// type NlxMetadata struct {
// 	Apps               []string `json:"apps"`
// 	AuthProviders      []string `json:"authproviders"`
// 	ComponentPacks     []string `json:"componentpacks"`
// 	DataServices       []string `json:"dataservices"`
// 	DataSources        []string `json:"datasources"`
// 	DesignSystems      []string `json:"designsystems"`
// 	Variables          []string `json:"variables"`
// 	Files              []string `json:"files"`
// 	Pages              []string `json:"pages"`
// 	PermissionSets     []string `json:"permissionsets"`
// 	SitePermissionSets []string `json:"sitepermissionsets"`
// 	Site               []string `json:"site"`
// 	Themes             []string `json:"themes"`
// }
type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps               []string `protobuf:"bytes,1,rep,name=Apps,proto3" json:"apps"`                              // @gotags: json:"apps"
	AuthProviders      []string `protobuf:"bytes,2,rep,name=AuthProviders,proto3" json:"authproviders"`            // @gotags: json:"authproviders"
	ComponentPacks     []string `protobuf:"bytes,3,rep,name=ComponentPacks,proto3" json:"componentpacks"`          // @gotags: json:"componentpacks"
	DataServices       []string `protobuf:"bytes,4,rep,name=DataServices,proto3" json:"dataservices"`              // @gotags: json:"dataservices"
	DataSources        []string `protobuf:"bytes,5,rep,name=DataSources,proto3" json:"datasources"`                // @gotags: json:"datasources"
	DesignSystems      []string `protobuf:"bytes,6,rep,name=DesignSystems,proto3" json:"designsystems"`            // @gotags: json:"designsystems"
	Variables          []string `protobuf:"bytes,7,rep,name=Variables,proto3" json:"variables"`                    // @gotags: json:"variables"
	Files              []string `protobuf:"bytes,8,rep,name=Files,proto3" json:"files"`                            // @gotags: json:"files"
	Pages              []string `protobuf:"bytes,9,rep,name=Pages,proto3" json:"pages"`                            // @gotags: json:"pages"
	PermissionSets     []string `protobuf:"bytes,10,rep,name=PermissionSets,proto3" json:"permissionsets"`         // @gotags: json:"permissionsets"
	SitePermissionSets []string `protobuf:"bytes,11,rep,name=SitePermissionSets,proto3" json:"sitepermissionsets"` // @gotags: json:"sitepermissionsets"
	Site               []string `protobuf:"bytes,12,rep,name=Site,proto3" json:"site"`                             // @gotags: json:"site"
	Themes             []string `protobuf:"bytes,13,rep,name=Themes,proto3" json:"themes"`                         // @gotags: json:"themes"
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *Metadata) GetAuthProviders() []string {
	if x != nil {
		return x.AuthProviders
	}
	return nil
}

func (x *Metadata) GetComponentPacks() []string {
	if x != nil {
		return x.ComponentPacks
	}
	return nil
}

func (x *Metadata) GetDataServices() []string {
	if x != nil {
		return x.DataServices
	}
	return nil
}

func (x *Metadata) GetDataSources() []string {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *Metadata) GetDesignSystems() []string {
	if x != nil {
		return x.DesignSystems
	}
	return nil
}

func (x *Metadata) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Metadata) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Metadata) GetPages() []string {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Metadata) GetPermissionSets() []string {
	if x != nil {
		return x.PermissionSets
	}
	return nil
}

func (x *Metadata) GetSitePermissionSets() []string {
	if x != nil {
		return x.SitePermissionSets
	}
	return nil
}

func (x *Metadata) GetSite() []string {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Metadata) GetThemes() []string {
	if x != nil {
		return x.Themes
	}
	return nil
}

var File_metadata_proto protoreflect.FileDescriptor

var file_metadata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x3a, 0x0a, 0x10,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x10, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x0f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x4e, 0x6c, 0x78, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x4e, 0x6c,
	0x78, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x57, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xa6, 0x03, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x41, 0x70, 0x70, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x41,
	0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x0e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x65,
	0x73, 0x69, 0x67, 0x6e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x53, 0x69, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12,
	0x53, 0x69, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x73,
	0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x42, 0x20,
	0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x75,
	0x69, 0x64, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData = file_metadata_proto_rawDesc
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_metadata_proto_rawDescData)
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_metadata_proto_goTypes = []interface{}{
	(*RetrievalPlan)(nil), // 0: protobuf.RetrievalPlan
	(*Plan)(nil),          // 1: protobuf.Plan
	(*Metadata)(nil),      // 2: protobuf.Metadata
}
var file_metadata_proto_depIdxs = []int32{
	1, // 0: protobuf.RetrievalPlan.CloudDataService:type_name -> protobuf.Plan
	1, // 1: protobuf.RetrievalPlan.MetadataService:type_name -> protobuf.Plan
	2, // 2: protobuf.Plan.NlxMetadata:type_name -> protobuf.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrievalPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_rawDesc = nil
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
